# Generated by Django 3.1.3 on 2020-11-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Song or playlist name')),
                ('tagid', models.CharField(max_length=50)),
                ('volume', models.FloatField()),
                ('uri', models.TextField()),
                ('source', models.SmallIntegerField(choices=[(1, 'spotify')])),
            ],
        ),
    ]
